import pytest

from src.services.monitoring_service import monitoring_service
from src.tm1.service import tm1_integration_service


@pytest.mark.asyncio
async def test_circuit_breaker_reads_closed_after_real_success(
    db_session, live_connection
):
    """Proves peek_circuit_breaker() reflects genuine TM1py-level success —
    a mocked client can't tell us this, since a mock never actually fails
    for real reasons (network, auth, server-side errors)."""

    org, user, connection = live_connection

    await tm1_integration_service.list_cubes(db_session, connection.id, org.id)

    statuses = await monitoring_service.get_tm1_status(db_session, org.id)
    status_by_id = {entry["connection_id"]: entry for entry in statuses}

    assert connection.id in status_by_id
    assert status_by_id[connection.id]["state"] == "closed"
    assert status_by_id[connection.id]["failure_count"] == 0


@pytest.mark.asyncio
async def test_usage_summary_endpoint_does_not_error_against_real_data(
    db_session, live_connection
):
    org, user, connection = live_connection

    # No AI usage has necessarily been generated by this test run, so this
    # only asserts the aggregation query itself doesn't error — see
    # test_ai_tools.py for a case that actually generates AI usage first.
    summary = await monitoring_service.get_usage_summary(db_session, org.id, days=30)

    assert "total_requests" in summary
    assert "by_model" in summary
