import json
import uuid

from sqlalchemy.ext.asyncio import AsyncSession

from src.ai.tools.base import Tool
from src.core.exceptions import PermissionDeniedException, ValidationException
from src.repositories.auth_repository import auth_repository
from src.tm1.client.connection_manager import tm1_connection_manager
from src.tm1 import governance
from src.tm1.deployment.change_service import change_service
from src.tm1.service import tm1_integration_service
from src.tm1.services import process_service

# First line of code the assistant drafts. A TI and rule comment both
# start with '#', so the marker is inert on the server and stays with the
# code after deployment: anyone reading the process later can see where it
# came from. Checked before adding, so re-proposing does not stack it.
AI_GENERATED_MARKER = (
    "# AI GENERATED by PA-Copilot. Reviewed and approved by a person before "
    "deployment."
)


def mark_ai_generated(code: str) -> str:
    if "AI GENERATED" in code[:500]:
        return code
    return f"{AI_GENERATED_MARKER}\n{code}"


_HUMAN_REVIEW_NOTE = (
    "This is a DRAFT only — it has NOT been applied to the TM1 server. "
    "A human administrator with deploy rights must review and execute it "
    "in the console."
)


async def _create_draft(
    db: AsyncSession,
    *,
    organization_id: uuid.UUID,
    user_id: uuid.UUID,
    connection_id: str,
    change_type: str,
    target_name: str,
    new_content: dict,
) -> str:
    # The assistant is read-only on PROD (src/tm1/governance.py).
    governance.check_ai_may_draft(
        await tm1_integration_service.get_connection(
            db, uuid.UUID(str(connection_id)), organization_id
        )
    )

    change = await change_service.create_change(
        db,
        connection_id=uuid.UUID(str(connection_id)),
        organization_id=organization_id,
        created_by=user_id,
        change_type=change_type,
        target_name=target_name,
        new_content=new_content,
    )

    return json.dumps(
        {
            "draft_change_id": str(change.id),
            "status": change.status,
            "validation_errors": change.validation_errors or [],
            "impact": change.impact or [],
            "note": _HUMAN_REVIEW_NOTE,
        }
    )


class ProposeRuleUpdateTool(Tool):

    name = "propose_rule_update"
    description = (
        "Propose an update to a cube's rules as a DRAFT change for human "
        "review. The draft includes impact analysis from the metadata "
        "graph. You cannot execute changes — a human administrator "
        "deploys drafts."
    )
    required_permission = "tm1.write"
    input_schema = {
        "type": "object",
        "properties": {
            "connection_id": {
                "type": "string",
                "description": "The ID of the TM1 connection.",
            },
            "cube_name": {
                "type": "string",
                "description": "The cube whose rules to update.",
            },
            "rules": {
                "type": "string",
                "description": "The complete proposed rule text.",
            },
        },
        "required": ["connection_id", "cube_name", "rules"],
    }

    async def execute(
        self,
        db: AsyncSession,
        *,
        organization_id: uuid.UUID,
        user_id: uuid.UUID,
        **kwargs,
    ) -> str:

        if not await auth_repository.user_has_permission(
            db, user_id, self.required_permission
        ):
            raise PermissionDeniedException(
                "You do not have permission to draft TM1 changes."
            )

        return await _create_draft(
            db,
            organization_id=organization_id,
            user_id=user_id,
            connection_id=kwargs["connection_id"],
            change_type="update_rules",
            target_name=str(kwargs["cube_name"]),
            new_content={
                "rules": mark_ai_generated(str(kwargs["rules"])),
                "ai_generated": True,
            },
        )


class ProposeProcessUpdateTool(Tool):

    name = "propose_process_update"
    description = (
        "Propose creating or updating a TurboIntegrator process as a DRAFT "
        "change for human review. The draft is compile-validated against "
        "the server without being saved. You cannot execute changes — a "
        "human administrator deploys drafts."
    )
    required_permission = "tm1.write"
    input_schema = {
        "type": "object",
        "properties": {
            "connection_id": {
                "type": "string",
                "description": "The ID of the TM1 connection.",
            },
            "process_name": {
                "type": "string",
                "description": "The process to create or update.",
            },
            "create_new": {
                "type": "boolean",
                "description": (
                    "true to create a new process, false to update an "
                    "existing one."
                ),
            },
            "prolog": {"type": "string", "description": "Prolog code."},
            "metadata": {"type": "string", "description": "Metadata code."},
            "data": {"type": "string", "description": "Data code."},
            "epilog": {"type": "string", "description": "Epilog code."},
            "datasource_type": {
                "type": "string",
                "enum": ["None", "ASCII"],
                "description": (
                    "Datasource. Use 'None' for a self-contained process. "
                    "Use 'ASCII' for a delimited-file loader — required for "
                    "source column variables (v1, v2, ...) to compile."
                ),
            },
            "datasource_name": {
                "type": "string",
                "description": (
                    "For ASCII: the data file path on the TM1 server "
                    "(the administrator can confirm or change it at deploy)."
                ),
            },
            "ascii_delimiter": {
                "type": "string",
                "description": "For ASCII: the column delimiter. Default ','.",
            },
            "ascii_header_records": {
                "type": "integer",
                "description": "For ASCII: header rows to skip. Default 0.",
            },
            "variables": {
                "type": "array",
                "description": (
                    "Datasource source columns, in order. Declare these so "
                    "references like v1, v2 compile against an ASCII/view "
                    "datasource."
                ),
                "items": {
                    "type": "object",
                    "properties": {
                        "name": {"type": "string"},
                        "type": {"type": "string", "enum": ["String", "Numeric"]},
                    },
                    "required": ["name", "type"],
                },
            },
            "parameters": {
                "type": "array",
                "description": (
                    "Process parameters (e.g. pSourceFile). Declare these so "
                    "the process compiles when the code references them."
                ),
                "items": {
                    "type": "object",
                    "properties": {
                        "name": {"type": "string"},
                        "type": {"type": "string", "enum": ["String", "Numeric"]},
                        "value": {
                            "type": "string",
                            "description": "Default value (numbers as text).",
                        },
                        "prompt": {"type": "string"},
                    },
                    "required": ["name", "type"],
                },
            },
        },
        "required": ["connection_id", "process_name", "create_new"],
    }

    async def execute(
        self,
        db: AsyncSession,
        *,
        organization_id: uuid.UUID,
        user_id: uuid.UUID,
        **kwargs,
    ) -> str:

        if not await auth_repository.user_has_permission(
            db, user_id, self.required_permission
        ):
            raise PermissionDeniedException(
                "You do not have permission to draft TM1 changes."
            )

        new_content: dict = {
            key: str(kwargs[key])
            for key in ("prolog", "metadata", "data", "epilog")
            if key in kwargs
        }

        # Mark the first tab the draft supplies (the Prolog when there is
        # one); a new process with no code at all gets a Prolog carrying
        # only the marker.
        first = next(
            (k for k in ("prolog", "metadata", "data", "epilog") if k in new_content),
            None,
        )
        if first is None and kwargs.get("create_new"):
            first = "prolog"
            new_content["prolog"] = ""
        if first is not None:
            new_content[first] = mark_ai_generated(new_content[first])
        new_content["ai_generated"] = True

        # Datasource / variable / parameter definitions travel as-is (lists
        # and scalars); _build_process applies them to the TM1py Process so
        # source columns and parameters resolve at compile time.
        for key in (
            "datasource_type",
            "datasource_name",
            "ascii_delimiter",
            "ascii_header_records",
            "variables",
            "parameters",
        ):
            if kwargs.get(key) is not None:
                new_content[key] = kwargs[key]

        return await _create_draft(
            db,
            organization_id=organization_id,
            user_id=user_id,
            connection_id=kwargs["connection_id"],
            change_type=(
                "create_process" if kwargs["create_new"] else "update_process"
            ),
            target_name=str(kwargs["process_name"]),
            new_content=new_content,
        )


def copy_content(source_name: str, body: dict) -> dict:
    """Draft content for an exact copy of a process body.

    `source_body` is what gets built and deployed. The code tabs, datasource
    type, variables and parameters are repeated in the ordinary draft format
    so the review screen shows the code and static analysis can check it —
    without them every source variable would read as undefined.
    """

    datasource = body.get("DataSource") or {}

    return {
        "copy_of": source_name,
        "prolog": body.get("PrologProcedure") or "",
        "metadata": body.get("MetadataProcedure") or "",
        "data": body.get("DataProcedure") or "",
        "epilog": body.get("EpilogProcedure") or "",
        "datasource_type": datasource.get("Type") or "None",
        "variables": [
            {"name": variable["Name"], "type": variable.get("Type") or "String"}
            for variable in body.get("Variables") or []
        ],
        "parameters": [
            {
                "name": parameter["Name"],
                "type": parameter.get("Type") or "String",
                "value": (
                    "" if parameter.get("Value") is None else str(parameter["Value"])
                ),
                "prompt": parameter.get("Prompt") or "",
            }
            for parameter in body.get("Parameters") or []
        ],
        "source_body": body,
    }


class ProposeProcessCopyTool(Tool):

    name = "propose_process_copy"
    description = (
        "Propose an exact copy of an existing TurboIntegrator process under a "
        "new name, as a DRAFT change for human review. The copy is taken "
        "from the server, not retyped, so code, datasource, variables and "
        "parameters match the original. Use this whenever the user asks to "
        "copy, clone or duplicate a process; to change the copy afterwards, "
        "use propose_process_update on the new name. You cannot execute "
        "changes — a human administrator deploys drafts."
    )
    required_permission = "tm1.write"
    input_schema = {
        "type": "object",
        "properties": {
            "connection_id": {
                "type": "string",
                "description": "The ID of the TM1 connection.",
            },
            "source_process": {
                "type": "string",
                "description": "The existing process to copy.",
            },
            "new_process_name": {
                "type": "string",
                "description": (
                    "Name for the copy. Must not already exist. If the user "
                    "gave none, use the original name followed by ' - Copy'."
                ),
            },
        },
        "required": ["connection_id", "source_process", "new_process_name"],
    }

    async def execute(
        self,
        db: AsyncSession,
        *,
        organization_id: uuid.UUID,
        user_id: uuid.UUID,
        **kwargs,
    ) -> str:

        if not await auth_repository.user_has_permission(
            db, user_id, self.required_permission
        ):
            raise PermissionDeniedException(
                "You do not have permission to draft TM1 changes."
            )

        source = str(kwargs["source_process"]).strip()
        new_name = str(kwargs["new_process_name"]).strip()

        # TM1 object names are case-insensitive, so 'it_load data' is the
        # original, not a copy of it.
        if not new_name or new_name.lower() == source.lower():
            raise ValidationException(
                "The copy needs a name different from the original process."
            )

        connection = await tm1_integration_service.get_connection(
            db, uuid.UUID(str(kwargs["connection_id"])), organization_id
        )
        client = await tm1_connection_manager.get_client(connection)
        body = await process_service.get_process_body(client, connection.id, source)

        content = copy_content(source, body)

        draft = json.loads(
            await _create_draft(
                db,
                organization_id=organization_id,
                user_id=user_id,
                connection_id=str(connection.id),
                change_type="create_process",
                target_name=new_name,
                new_content=content,
            )
        )

        datasource = body.get("DataSource") or {}
        draft["copied_from"] = source
        draft["new_process_name"] = new_name
        draft["copy_summary"] = {
            "datasource_type": content["datasource_type"],
            "datasource_name": datasource.get("dataSourceNameForServer"),
            "parameters": [parameter["name"] for parameter in content["parameters"]],
            "variables": [variable["name"] for variable in content["variables"]],
            "code_lines": {
                tab: len((content[tab] or "").splitlines())
                for tab in ("prolog", "metadata", "data", "epilog")
            },
        }

        return json.dumps(draft)


_RUN_REVIEW_NOTE = (
    "This is a proposed RUN only — the process has NOT been run. A person "
    "with permission to run processes must open the draft, check the "
    "parameter values and what the process writes, and approve it. A run "
    "cannot be rolled back."
)


class ProposeProcessRunTool(Tool):
    """The only way the assistant can get a process run: by asking.

    It writes a `run_process` draft. Nothing reaches TM1 until a person
    holding tm1.deploy and tm1.execute approves that draft through the
    change API, which runs it once, never retries, and records TM1's
    answer on the change.
    """

    name = "propose_process_run"
    description = (
        "Propose running a TurboIntegrator process, with parameter values, "
        "as a DRAFT for a person to approve. You cannot run processes. The "
        "draft shows the approver every parameter with the value it will "
        "take (given or default) and the cubes the process writes. Parameter "
        "names are checked against the process. Propose a run only when the "
        "user asks for one, and say plainly that it waits for approval."
    )
    required_permission = "tm1.write"
    input_schema = {
        "type": "object",
        "properties": {
            "connection_id": {
                "type": "string",
                "description": "The ID of the TM1 connection.",
            },
            "process_name": {"type": "string", "description": "The process to run."},
            "parameters": {
                "type": "object",
                "description": (
                    "Parameter values by parameter name, e.g. {\"pYear\": \"2026\"}. "
                    "Omitted parameters take the process's defaults."
                ),
                "additionalProperties": {"type": ["string", "number"]},
            },
        },
        "required": ["connection_id", "process_name"],
    }

    async def execute(
        self,
        db: AsyncSession,
        *,
        organization_id: uuid.UUID,
        user_id: uuid.UUID,
        **kwargs,
    ) -> str:

        if not await auth_repository.user_has_permission(
            db, user_id, self.required_permission
        ):
            raise PermissionDeniedException(
                "You do not have permission to draft TM1 changes."
            )

        process_name = str(kwargs.get("process_name") or "").strip()

        if not process_name:
            raise ValidationException("process_name is required.")

        parameters = kwargs.get("parameters") or {}

        if not isinstance(parameters, dict):
            raise ValidationException("parameters must be an object of name to value.")

        draft = json.loads(
            await _create_draft(
                db,
                organization_id=organization_id,
                user_id=user_id,
                connection_id=str(kwargs["connection_id"]),
                change_type="run_process",
                target_name=process_name,
                new_content={"parameters": {str(k): v for k, v in parameters.items()}},
            )
        )
        draft["note"] = _RUN_REVIEW_NOTE

        return json.dumps(draft)
