"""add_tm1_changes

Revision ID: 3ebbf0d4e9ea
Revises: c3fa18f451f1
Create Date: 2026-07-22 06:14:08.745634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3ebbf0d4e9ea'
down_revision: Union[str, Sequence[str], None] = 'c3fa18f451f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tm1_changes',
    sa.Column('connection_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('change_type', sa.String(length=30), nullable=False),
    sa.Column('target_name', sa.String(length=255), nullable=False),
    sa.Column('new_content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('previous_content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('validation_errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('impact', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('executed_by', sa.UUID(), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rolled_back_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['tm1_connections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['executed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tm1_changes_connection_id'), 'tm1_changes', ['connection_id'], unique=False)
    op.create_index(op.f('ix_tm1_changes_created_by'), 'tm1_changes', ['created_by'], unique=False)
    op.create_index(op.f('ix_tm1_changes_organization_id'), 'tm1_changes', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tm1_changes_organization_id'), table_name='tm1_changes')
    op.drop_index(op.f('ix_tm1_changes_created_by'), table_name='tm1_changes')
    op.drop_index(op.f('ix_tm1_changes_connection_id'), table_name='tm1_changes')
    op.drop_table('tm1_changes')
    # ### end Alembic commands ###
