"""add_ai_tool_executions

Revision ID: 68f6214549b4
Revises: c64300f3fc95
Create Date: 2026-07-21 01:06:56.770020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '68f6214549b4'
down_revision: Union[str, Sequence[str], None] = 'c64300f3fc95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_tool_executions',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tool_name', sa.String(length=100), nullable=False),
    sa.Column('arguments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_tool_executions_conversation_id'), 'ai_tool_executions', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_ai_tool_executions_organization_id'), 'ai_tool_executions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_ai_tool_executions_user_id'), 'ai_tool_executions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_tool_executions_user_id'), table_name='ai_tool_executions')
    op.drop_index(op.f('ix_ai_tool_executions_organization_id'), table_name='ai_tool_executions')
    op.drop_index(op.f('ix_ai_tool_executions_conversation_id'), table_name='ai_tool_executions')
    op.drop_table('ai_tool_executions')
    # ### end Alembic commands ###
