"""add_tm1_metadata_graph

Revision ID: 7a3f6ef84a82
Revises: 68f6214549b4
Create Date: 2026-07-21 02:21:51.559237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a3f6ef84a82'
down_revision: Union[str, Sequence[str], None] = '68f6214549b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tm1_objects',
    sa.Column('connection_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('object_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['tm1_connections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connection_id', 'object_type', 'name', name='uq_tm1_objects_connection_type_name')
    )
    op.create_index(op.f('ix_tm1_objects_connection_id'), 'tm1_objects', ['connection_id'], unique=False)
    op.create_index(op.f('ix_tm1_objects_organization_id'), 'tm1_objects', ['organization_id'], unique=False)
    op.create_table('tm1_relationships',
    sa.Column('connection_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('from_object_id', sa.UUID(), nullable=False),
    sa.Column('to_object_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=False),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['tm1_connections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_object_id'], ['tm1_objects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_object_id'], ['tm1_objects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tm1_relationships_connection_id'), 'tm1_relationships', ['connection_id'], unique=False)
    op.create_index(op.f('ix_tm1_relationships_from_object_id'), 'tm1_relationships', ['from_object_id'], unique=False)
    op.create_index(op.f('ix_tm1_relationships_organization_id'), 'tm1_relationships', ['organization_id'], unique=False)
    op.create_index(op.f('ix_tm1_relationships_to_object_id'), 'tm1_relationships', ['to_object_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tm1_relationships_to_object_id'), table_name='tm1_relationships')
    op.drop_index(op.f('ix_tm1_relationships_organization_id'), table_name='tm1_relationships')
    op.drop_index(op.f('ix_tm1_relationships_from_object_id'), table_name='tm1_relationships')
    op.drop_index(op.f('ix_tm1_relationships_connection_id'), table_name='tm1_relationships')
    op.drop_table('tm1_relationships')
    op.drop_index(op.f('ix_tm1_objects_organization_id'), table_name='tm1_objects')
    op.drop_index(op.f('ix_tm1_objects_connection_id'), table_name='tm1_objects')
    op.drop_table('tm1_objects')
    # ### end Alembic commands ###
