"""add_user_registration_status

Revision ID: 8f0b76be1e6f
Revises: 3cefa817d843
Create Date: 2026-07-23 07:44:40.708024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f0b76be1e6f'
down_revision: Union[str, Sequence[str], None] = '3cefa817d843'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('registration_status', sa.String(length=20), server_default='approved', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'registration_status')
    # ### end Alembic commands ###
