"""add_tm1_connection_auth_type

Revision ID: c3fa18f451f1
Revises: 7a3f6ef84a82
Create Date: 2026-07-22 05:40:22.179747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3fa18f451f1'
down_revision: Union[str, Sequence[str], None] = '7a3f6ef84a82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tm1_connections', sa.Column('authentication_type', sa.String(length=20), server_default='native', nullable=False))
    op.add_column('tm1_connections', sa.Column('tenant', sa.String(length=100), nullable=True))
    op.add_column('tm1_connections', sa.Column('database', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tm1_connections', 'database')
    op.drop_column('tm1_connections', 'tenant')
    op.drop_column('tm1_connections', 'authentication_type')
    # ### end Alembic commands ###
